name: Lighthouse-CI
on:
  pull_request:
    branches: [main]
jobs:
  lighthouseCI:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install && npm install -g @lhci/cli@0.8.x
    - name: Build
      run: npm run build
    - name: Run Lighthouse
      run: lhci autorun
